### ISSUE TITLE
Some clarifications on "run" and "runs"

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/mlflow-original#1]
There seems to be two homonymous concepts called "run" in MLflow. The first is an *experiment run* (noun) which is associated with the Tracking component. The second is an action, to *run a project* (verb), meaning, running some code with the specified dependencies, which is associated with the Project component and confusingly can encompass one or more experiment (Tracking) runs. This latter definition corresponds to the `mlflow run` CLI command, and takes a directory or a repo, along with other parameters, e.g.

```
mlflow run git@github.com:databricks/mlflow-example.git -P alpha=0.5
```

Therefore, if we want `mlflow_run()` to correspond to this, we wouldn't do something like `mlflow_run("train.R")` or `R -e "mlflow::mlflow_run('train.R')"` as outlined at https://github.com/rstudio/mlflow/blob/3b4f743bc01cc22a673f54b64bffc7bef85a8bb9/README.Rmd#projects. Rather, the user would execute something like `mlflow_run("path/to/proj", alpha = 0.5, foo = 32)`.

Going back to the experiment run, our initial design is to allow two cases:
1. One file is associated with one experiment run: in this case, the run starts at the top of the file, and ends at the end of the file.
2. One file is associated with multiple runs: in this case, the runs start/end at `#* @mlflow-run` annotations and the end of the file. Alternatively, the user can wrap each run in a `mlflow_run({})` block (note the confusion here with `mlflow_run()`).

In the Python API, the user can control when the run starts/ends by enclosing it in a `with` block. To support this in R, we'd need to require users to annotate `#* @mlflow-run-start` and `#* @mlflow-run-end` even in "single run" files or wrap runs in functions. One use case here would be that the user doesn't want some data preprocessing to be included in the timing of the runs.

Finally, users can choose to utilize either/both/neither Tracking and Project, so it may not make sense to create a `MLProject` file when an experiment run is triggered, or launch the server when a project is created. A corollary to this is that we shouldn't force the user to run an experiment if all she wants to do is create a project.

**Comment by jjallaire** [comment]
Let's try to discuss the implications of this realtime on Monday (I'm pretty free during the middle of the day). 

I think that we want to support an API like the Python API (where you can scope your run code explicitly -- for this case I really think we need actual R code not magic comments but we can discuss on Monday). However, we will also want to support a simplistic mode where it's a run per file.

Anyway, it will be too confusing to try to run this down async, let's just talk Monday.

**Comment by jjallaire** [comment]
So we definitely want mlflow_run to correspond to the CLI. I'd say it should be able to take either a directory (as in your example) or a source file (which just implies that source files directory and use that file as the entry point). All of these should work:

```r
mlflow_run(".")
mlflow_run("my/project/dir")
mlflow_run("train.R")
mlflow_run("my/project/dir/train.R")
```

For defining run scopes I think we want a actual R code rather than magic comments (since the R code is executable). We could literally use the `with` syntax of Python for this (with is an R S3 generic). So have the following functions and behaviors:

```r
mlflow_start_run()
# run code here
mlflow_end_run()

with(mlflow_start_run(), {
   # run code here
})
```

I think given that this is a slightly more advanced use case and given the fact that we can mirror the Python API exactly that this is what we should aspire to.

Okay, sorry. I know I said no more async discussions but this got a bit clearer in my head re-reading your writeup and wanted to record my thoughts.
