### ISSUE TITLE
Set up codecov

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/mlflow-original#28]
@javierluraschi could you look into this when travis is set up?

**Comment by javierluraschi** [comment]
Yeah, took a quick look... the challenge here is that we can't upload code coverage from the R test since it would override the Python code coverage, we will have to trigger R coverage while running the python tests... which means we should also add some python tests, something to add at some point.

**Comment by javierluraschi** [comment]
Wait! https://docs.codecov.io/docs/merging-reports

> Codecov will merge the reports automatically while maintaining the original upload context.

**Comment by javierluraschi** [comment]
https://codecov.io/gh/rstudio/mlflow
