### ISSUE TITLE
Improvements to model serialization

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/mlflow-original#7]

**Comment by kevinykuo** [comment]
There are a couple ways to go about the (serving) model definition and serialization API. The first is to allow the user to define a top-level serving function, and we do our best to infer what we need to keep.

```{r}
# train model

fn <- function(inputs) {
  # make predictions
}

mlflow_save_model(fn)
```

We'd inspect the body of `fn()` and figure out the environments where the symbols live. There are, however, a couple scenarios that we can't engineer around (credit goes to Lionel for coming up with these). The first is a "false positive", where we capture more than is needed:

```{r}
var <- c(very, large, data) # False positive

df  <- tibble(var = 1:5)

fn <- function(inputs) {
  temp_data <- mutate(df, var * 3)
  # Make prediction
  )
```

The second is a "false negative", where we don't capture something we need:

```{r}
x <- 100 # False negative
vars <- c("cyl", "am")

fn <- function(inputs) {
  exprs <- map(vars, ~ sprintf("%s * x", .x))
  temp_data <- mutate(mtcars, !!!parse_exprs(exprs))
  # Make prediction
}
```

To get around this, the second approach would be to require users to define the closure within a provided function (similar to `base::local()`), e.g.

```{r}
model <- lm(...)
fn <- box({
  # Pull in stuff if needed
  model <- model
  function(inputs) {
    # Make prediction
    predict(model, inputs)
  }
})

mlflow_save_model(fn)
```

We can also support unquoting:

```{r}
model <- lm(...)
fn <- box(function(inputs) {
  # Inline the model object
  predict(!!model, inputs)
})

mlflow_save_model(fn)
```

We could potentially get around the false negatives by saving *everything*, but of course that can potentially be expensive.

cc @jjallaire

**Comment by jjallaire** [comment]
I think it's fine if we say that *usually* automatically capture all the right stuff, and then just document how to work around if we over or under save objects (as you have done here).

**Comment by kevinykuo** [comment]
Putting this on hold for a little bit. Going to coordinate with @hadley @lionel- to see if we can/should come up with a general (and timely) solution to this, since a feature like this is also in the scope of rlang.

**Comment by lionel-** [comment]
Ideally we would use the same mechanism for callr, sparklyr, mlflow, and everywhere we need to send some computations to a remote. There are two issues related to sending a function to a remote: objects (and sometimes functions) from the global environment and functions (and sometimes objects) from the search path.

My current thinking about this problem is that global objects should be pulled into a local environment while symbols from the search path should be lazily loaded within that environment (more precisely, one level up). This would be directly compatible with the base serialiser/unserialiser.

We probably need two constructors, a strict and a dwim (do-what-I-mean) variants. With the strict constructor the user would have to make sure its function is self-contained by pulling the relevant data manually and prefixing all functions with a namespace. On the other hand the convenient dwim version would pull down global data automatically and create lazy aliases for functions from the search path.


### Strict constructor

Pulling global objects to a local environment is immediately compatible with `base::serialize()`. Only the global environment and the search path are ignored by `serialize()`, so if you create a local closure with data pulled in its local environment, the function is ready to be sent over:

```r
data <- mtcars

fn <- local({
  data <- data
  function() somepkg::do(data)
})

serialize(fn, conn)
```

We could offer a `local()` variant that evaluates iteratively like `tibble()`. All named expressions would be assigned in the local environment. This way the user doesn't have to use `<-` within a `{` block, which makes for a more conventional interface I think. The last expression should evaluate to a function:

```r
fn <- external(
  data = data,
  foo = toupper(letters),

  function() {
    somepkg::do(data, foo)
  }
)
```

That is all we need for the strict constructor: the user is explicit about the objects to pull with the function and uses namespace prefixes to call package tools.


### Automatic pulling of globals

In general scanning an expression to look for object definitions is a bit sloppy because of false positives and false negatives, as Kevin mentioned above. Under-pulling objects can be worked around by pulling them explicitly but over-pulling objects can't really be worked around. Trading slopiness for convenience seems reasonable in R but we should make it easy for users to make their functions self-contained.


#### Print method

Under-pulling objects will normally cause an error on the remote that the user will detect and fix. On the other hand over-pulling objects might easily go unnoticed and slow things down. @hadley had a great idea to make things more explicit: print all pulled objects along with their size. `external()` would add a class to the function with a print method:

```r
fn
#> <external>
#> Objects:
#>   * data: 3MB
#>   * foo: 10KB
#> function() {
#>   somepkg::do(data, foo)
#> }
```

With this printed information users can make sure everything is correct before sending a function over.


#### Lambda syntax

The interaction-friendly dwim constructor needs a short function name and I think purrr's lambda-formula syntax would work great here:

```r
ext(~somepkg::do(data, foo))
#> <external>
#> Objects:
#>   * data: 3MB
#>   * foo: 10KB
#> function(..., .x = ..1, .y = ..2, . = ..1) {
#>   somepkg::do(data, foo)
#> }
```

As in purrr, the lambda syntax automatically defines `.`, `.x` and `.y` arguments. Because these arguments can be left unused without error, the lambda shortcut is compatible with UIs expecting any sort of arity (zero like callr, one like mlflow, etc).

It would make sense for UI's to use `as_external()` which would be defined like this:

```r
as_external <- function(x) {
  if (is_external(x)) {
    x
  } else {
    ext(x)
  }
}
```

This allows the user to pass an external function defined explicitly or a formula with implicit pulling:

```r
# Explicit:
fn <- external(identity)
mlflow_save_model(fn)

# Implicit:
mlflow_save_model(~ .x)
```


#### Pulling of global functions

The external function might rely on user-defined global functions. These should be pulled as well.

```r
mytoupper <- toupper

ext(~mytoupper("foo"))
#> <external>
#> Functions:
#>   * mytoupper(): 2.74KB
#> function(..., .x = ..1, .y = ..2, . = ..1) {
#>   mytoupper("foo")
#> }
```

Since those functions might themselves rely on objects from the global env, the search for globals should iterate over these closures:

```r
prefix <- "baz_"
myprefixer <- function(x) paste0(prefix, x)

ext(~myprefixer("foo"))
#> <external>
#> Objects:
#>   * prefix: 112B
#> Functions:
#>   * myprefixer(): 2.74KB
#> function(..., .x = ..1, .y = ..2, . = ..1) {
#>   myprefixer("foo")
#> }
```


### Search path

Now comes the question of the packages in scope at the time the external function is created. With the explicit constructor, the user is in charge of making sure the function is self-contained by prefixing all function calls with a namespace. With the auto-pulling semantics of the formula constructor however it will probably be natural for users to refer to functions from the search path without any prefix. I see three solutions to this problem: fake search paths, auto-prefixing, and lazily loaded masking.


#### Fake search paths

I experimented last year with the idea of recreating fake search paths around closures: <https://github.com/lionel-/rlanglabs/blob/master/R/serial.R>.

On hindsight this doesn't seem the right approach because of its complexity and potentially lurking problems.


#### Namespace prefixes

Prefixing function symbols with a namespace would be a simpler approach that can be done before serialisation and that doesn't require any post-processing on the remote side.

We'd look in the search path for definitions of symbols in function position and insert the relevant namespaces:

```r
library("somepkg")
data <- mtcars

ext(~do(data))
#> <external>
#> Objects:
#>   * data: 7.21KB
#> function(..., .x = ..1, .y = ..2, . = ..1) {
#>   somepkg::do(data)
#> }
```

This seems simple on a first approach but is actually quite problematic. What should we do about user-defined operators? Calling those in prefix form would look weird when printed. And wouldn't work with magrittr because it is an NSE operator that doesn't support being called in namespace form. The following would throw an error on the remote:

```r
library("tidyverse")

ext(~mtcars %>% select(cyl))
#> <external>
#> function(..., .x = ..1, .y = ..2, . = ..1) {
#>   dplyr::`%>%`(datasets::mtcars, dplyr::select(foo))
#> }
```

Another difficulty has to do with objects referring to functions, for instance passed to `lapply()`. We'd have to prefix those symbols as well:

```r
ext(~lapply(mtcars, var))
#> <external>
#> function(..., .x = ..1, .y = ..2, . = ..1) {
#>   base::lapply(datasets::mtcars, stats::var)
#> }
```

But now we get serious bugs whenever we can't detect that a symbol does not actually refer to a function from the search path:

```r
data <- tibble(x = 1, var = 2)
ext(~mutate(data, x = x * var))
#> <external>
#> Objects:
#>   * data: 1KB
#> function(..., .x = ..1, .y = ..2, . = ..1) {
#>   dplyr::mutate(datasets::data, x = x * stats::var)
#> }
```

Auto-prefixing is likely a dead-end.


#### Lazy aliases

I think the most robust approach would be to pull the function themselves in the local environment along the other objects. These should be one level up to allow for objects and functions with the same name.

However we don't want to pull the actual function definitions in there, mainly because this wouldn't be robust to variations in package versions. The local definition might be calling internal functions that don't exist on the remote or have a different interface etc.

The solution is to use active bindings that resolve to the relevant function. Active bindings are correctly serialised/unserialised up to at least R 3.1. For instance `purrr::map()` would be imported as such:

```r
makeActiveBinding("map", function() purrr::map, env)
```

Then we keep the original function definition, this is compatible with the base serialiser, with NSE, etc. I can't think of a way to cause this scheme to fail.

```r
data <- tibble(x = 1, var = 2)
ext(~data %>% mutate(x = x * var))
#> <external>
#> Objects:
#>   * data: 1KB
#> Aliases:
#>   * dplyr: `%>%`, mutate()
#>   * stats: var()
#> function(..., .x = ..1, .y = ..2, . = ..1) {
#>   data %>% mutate(x = x * var)
#> }
```

Side note, the external function object would keep all dependent packages and their versions in an attribute. Then the remote could throw warnings if the package version is older than locally.

cc @gaborcsardi as this is relevant for callr.

**Comment by gaborcsardi** [comment]
I like the strict method. :) 

For the  magical method, I think I would prefer sg that does not copy all global objects by default. Maybe sg like this, in spirit: https://github.com/henrikbengtsson/globals

I am not entirely sure why you would pull the global objects into an env, is that because you want to use the default serializer? Can't we just serialize those manually, and then unserialize them into the global env of the other process? I think it is worth trying  to recreate the same environment in the other process, unless we have a good reason not to.

**Comment by lionel-** [comment]
> For the magical method, I think I would prefer sg that does not copy all global objects by default. 

It does not copy all global objects, only those for which we detect a symbol.

> I am not entirely sure why you would pull the global objects into an env, is that because you want to use the default serializer?

I like that it makes it self-contained. This makes it more useful for remotes that are kept alive as different computations can be sent over without interactions. Is there a useful case for incurring side effects on the global env and search path?

**Comment by gaborcsardi** [comment]
> Is there a useful case for incurring side effects on the global env and search path?

Anything that refers to the global env, either explicitly, or via  `<<-`, might not work. Yes, people should not refer to the global env, but it is probably not a coincidence that CRAN has a check for this. I would guess that it is also more common in non-package code.

**Comment by lionel-** [comment]
Right but do you know of specific interesting cases? Failure to pick up globals because of string-metaprogramming would be a more common problem I think.

One source of problems might be `source()` which defaults to the global env. There'd be no issue for first-time definitions but an object might fail to be redefined if the function calls `source()` or `sourceCpp()`. I'm not sure sourcing files on remotes is practical in general though. And such redefinitions are probably rare anyway?

**Comment by gaborcsardi** [comment]
That's the thing, by recreating the same environment and copying the global env to global env, we don't have to deal with these issues. It would also protect us against future changes in base R. Think about things like the recent S3 lookup changes.

I think we either have a stateless external process, in which case we clear the global env and everything, or start a new process; or we have a stateful external process, in which case it is fine to put things in the global env if they are there in the master process.

I would even consider recreating the search path, unless of course you are sure that that's not a good idea. E.g. how about recreating the search path via object tables? And serve functions from the  search path on demand? Is that a bad idea?

**Comment by lionel-** [comment]
About `source()`, it might make sense to mask all side-effecty functions like `library()`, `attach()` etc to throw an error indicating that's not supported and these functions should be called locally rather than on the remote. Unless we override the base namespace definitions we'll miss some indirect calls, but they're probably pretty rare since packages should not call these. So the general advice would be: load everything you need locally and that will be sent along with the function.

> I would even consider recreating the search path, unless of course ... Is that a bad idea?

That was the first idea that I worked on. After discussion with Hadley I started to look for simpler solutions because it feels unnecessarily complex. It requires post-processing on the remote, unlike the local closure which can be run immediately after unserialisation.

Fake search paths will throw off some R code, for example the new dispatch semantics check  for the `R_GlobalEnv` pointer. Though that is harmless in this case, there may be lurking problems here.

> It would also protect us against future changes in base R. Think about things like the recent S3 lookup changes.

The new dispatch semantics make things easier because we don't have to search for potential methods in the search path. But I agree that future updates are a concern, though I'm not too worried because R is designed to be run from outside the global environment (e.g. package system). Overall I still think the local closures is a better bet than the fake search path and fake global env.

But you're probably right that it is better to avoid complications when it's ok to have side effects on the remote. There could be a different method with no impact on the UI. It'd be easy to implement, just serialise a `{ }` expression with some `<-` with data inlined and some `library()` calls. For example:

```r
expr({
  # Import data in the global env
  data <- !!data
  foo <- !!foo

  # Attach packages
  library("tidyverse")

  # Return (or call?) user function
  !!fn
})
```

@kevinykuo @javierluraschi Does it make sense to avoid side effects in your case or is the R session a throwaway?

**Comment by lionel-** [comment]
> So the general advice would be: load everything you need locally and that will be sent along with the function.

One way of framing the local bindings method is that it captures the current state of the R session into an `imports` environment created around the function. This has limitations but those are the same as for namespaced code in packages. It also has the same advantages: the external function is insulated from the state of the session on the remote by the imports env. I find this appealing.

**Comment by kevinykuo** [comment]
@lionel- in both mlflow and sparklyr, the "remote" sessions are inherently stateless, since the services exposed need to be scalable. I can't imagine any use case where the user might want to write `<<-` or mess with the global environment. That said, the way this is implemented is going to be mostly invisible to the users.

Regarding the API, I think the explicit construction makes sense when users want full control of what to ship, but it'd be worthwhile to have a simple API without any wrappers or introducing new syntax if users can bear the risk of overserializing, e.g.

```
mlflow_save_model(function(input, model) {"make prediction"})
```
I'm assuming we get this for free if the labmda syntax is supported, but let me know if that's not right.

**Comment by lionel-** [comment]
> I'm assuming we get this for free if the labmda syntax is supported, but let me know if that's not right.

Yup the idea would be to apply `as_external()` to the argument of `mlflow_save_model()`. Then the user can supply a lambda formula, an external function created with the strict constructor, or just a function. In the latter case, I guess we want to apply the same magic as for the formula?

**Comment by javierluraschi** [comment]
I performed a basic implementation using the serving function formals as the context that we store in the persisted model; mostly, since I wanted to have this repo functional. That said, I'm happy to scratch this out when we implement better ways to serialize the closure.

**Comment by javierluraschi** [comment]
From a chat with Lionel and Kevin, we believe we want an explicit approach using an `external()` helper for the short term, and longer term, we will reuse `rlangs` newer features to perform serialization automatically, code snippet we wrote:

```r
# latest short-term design
mlflow::mlflow_save_model(
  external(
    a = a,
    function() {
      a
    }
  )
)

# considered but rejected
mlflow::mlflow_save_model(
  a = a,
  function() {
    a
})

# considered but rejected
mlflow::mlflow_save_model(function(context) {
  context$a
}, context = list(a = a))
```

**Comment by lionel-** [comment]
This functionality will live in a package called `external`. I'm thinking the constructor should be named `ext()` to be shorter. Will send it on github soon tonight or tomorrow.

**Comment by lionel-** [comment]
After discussion with Kevin and Javier the function will be called `crate()`, which is suggestive of packaging something up for transportation.

PR at https://github.com/r-lib/external/pull/1

**Comment by kevinykuo** [comment]
I'm marking this done, thanks @lionel- and others for putting this together!!
